Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2018-09, with the labels that each got.

#684 Port convert anonymous class creation to lambda expression from JDT.UI
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractMultiFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpContext.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpRequirements.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/ICleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/IMultiFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MapCleanUpOptions.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.properties
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/PotentialProgrammingProblemsCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SerialVersionSubProcessor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/FixCorrectionProposal.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/ModifierCorrectionSubProcessor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/GetterSetterQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassCreationToLambdaTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Labels: CQ required

#785 Status message 'Updating Maven projects' shows progress more than 100%
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
Labels: bug, in progress

#786 Add enable/disable completion option
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
Labels: enhancement, in progress

#788 Update m2e to 1.9.1.20180906-0204
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: in progress

#790 Migrate to lsp4j 0.5.x
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
Labels: in progress

#795 Wait for lifecycle jobs before returning document symbols
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Labels: in progress

#808 Update buildship to 2.2.2.v20180918-2317-s
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: in progress

#809 Add Java 11 tests
  org.eclipse.jdt.ls.tests/fakejdk/11/DELETE_ME_WHEN_USING_ACTUAL_JDK11_API_STUBS
  org.eclipse.jdt.ls.tests/fakejdk/11/rtstubs.jar
  org.eclipse.jdt.ls.tests/fakejdk/README.TXT
  org.eclipse.jdt.ls.tests/projects/eclipse/java11/.classpath
  org.eclipse.jdt.ls.tests/projects/eclipse/java11/.project
  org.eclipse.jdt.ls.tests/projects/eclipse/java11/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/java11/src/main/java/foo/bar/Foo.java
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradlew
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradlew.bat
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/settings.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/src/main/java/foo/bar/Foo.java
  org.eclipse.jdt.ls.tests/projects/maven/salut-java11/pom.xml
  org.eclipse.jdt.ls.tests/projects/maven/salut-java11/src/main/java/org/sample/Bar.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/TestVMType.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractGradleBasedTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Labels: in progress
