Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2019-07, with the labels that each got.

#1078 Prevent aggressive classpath updates when jars don't change
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java
Labels: bug

#1095 Fix ChangeUtil for non-MultiTextEdit conversion
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
Labels: bug

#1106 Refactor ChangeUtil: universal API converting Change to WorkspaceEdit
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ChangeUtil.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/GetRefactorEditHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ChangeUtilTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java
Labels: debt

#1112 Properly filter code actions according to context.only values
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/SourceAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/OrganizeImportsActionTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AdvancedExtractTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractConstantTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractVariableTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/GetRefactorEditHandlerTest.java
Labels: bug

#1113 Enable the 'Invert conditions' fix
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/AdvancedQuickAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/InvertConditionTest.java
Labels: code-actions, enhancement

#1116 Replace fixes and cleanups now provided by jdt.core.manipulation
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractMultiFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/AbstractSerialVersionOperation.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpContext.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/CleanUpRequirements.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/ICleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/IMultiFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/LambdaExpressionsFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MapCleanUpOptions.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/MultiFixMessages.properties
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/PotentialProgrammingProblemsCleanUp.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/PotentialProgrammingProblemsFix.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/SerialVersionDefaultOperation.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/fix/SerialVersionHashOperation.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/SerialVersionSubProcessor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/FixCorrectionProposal.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
Labels: debt

#1120 Convert lambda to anonymous class creation
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/LambdaToAnonymousClassCreationTest.java
Labels: code-actions
