Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2019-09, with the labels that each got.

#1173 Add org.eclipse.ant.core into the launch config
  launch/jdt.ls.remote.server.launch
  launch/jdt.ls.socket-stream.launch
Labels: build/infra

#1165 Navigate to the super implementation
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FindLinksHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FindLinksHandlerTest.java
Labels: enhancement

#1195 Update Buildship to 3.1.2
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: enhancement, gradle
