Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2020-05, with the labels that each got.

#1437 Respect 'java.codeGeneration.generateComments' when generating accessors on completion
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/GetterSetterCompletionProposal.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: bug, content-assist

#1438 jdt.ls shouldn't modify disk file when handling newly created or renamed files
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
Labels: bug

#1439 Discard the stale workingcopies that belonged to the deleted folder
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventsHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceEventHandlerTest.java
Labels: bug

#1434 Check for suspicious gradle-wrapper.jar
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ExceptionFactory.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JobHelpers.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/DownloadChecksumJob.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/HashProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/ValidationResult.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/gradle.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/gradlew
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/gradlew.bat
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/settings.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/src/main/java/Library.java
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-4.0/src/test/java/LibraryTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/WrapperValidatorTest.java
Labels: enhancement, gradle

#1454 Can get VM installation path through ProjectCommand.getProjectSettings()
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
Labels: enhancement
