Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2020-06, with the labels that each got.

#1470 Correctly assign the queueLength in WrapperValidator
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/internal/gradle/checksums/WrapperValidator.java
Labels: bug

#1473 Fix NPE in BaseDocumentLifeCycleHandler.publishDiagnostics
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
Labels: bug

#1478 Update to Eclipse 4.16
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractConstantRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractFieldRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractMethodRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/code/ExtractTempRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/reorg/ReorgPolicyFactory.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/sef/SelfEncapsulateFieldRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/highlighting/SemanticHighlightings.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/pom.xml
Labels: build/infra, enhancement

#1477 Support annotations in semantic highlighting
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/TokenType.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/SemanticTokensCommandTest.java
Labels: enhancement, semantic highlighting

#1484 Optimize default VM management to avoid unnecessary project updates
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseInitHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.tests.syntaxserver/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.tests.syntaxserver/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/JVMConfiguratorTest.java
Labels: enhancement, performance

#1485 Avoid unnecessary Gradle re-synch on restart
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradlew
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradlew.bat
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/settings.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/src/main/java/Library.java
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/src/test/java/LibraryTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Labels: enhancement, gradle, performance
