Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2021-12, with the labels that each got.

#1967 Use CreateFileChange from org.eclipse.jdt.ls.core
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
Labels: bug, regression

#1972 Remove LOG4J from builds.
  launch/jdt.ls.remote.server.launch
  launch/jdt.ls.socket-stream.launch
  launch/jdt.ls.socket-stream.syntaxserver.launch
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra, dependencies

#1969 DocumentLifeCycleHandlerTest.testFixInDependencyScenario fails randomly
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Labels: regression
