Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2021-08, with the labels that each got.

#1829 Update eclipse-jarsigner-plugin to 1.3.2.
  pom.xml
Labels: build/infra

#1843 Update Maven wrapper to 3.8.2
  .mvn/wrapper/maven-wrapper.properties
Labels: build/infra

#1850 fix: Cannot exclude maven sub-module
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetectorTest.java
Labels: bug

#1857 evaluate generic server-side snippets in resolve stage
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: performance, completion
