Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2022-09, with the labels that each got.

#2216 Java LS builds fail
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-12/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-12/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-13/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-13/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-14/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-14/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-withoutjava/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-withoutjava/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/multi-module/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/multi-module/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/sample/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/sample/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/subprojects/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/subprojects/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/multi-buildtools/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/multi-buildtools/gradle/wrapper/gradle-wrapper.properties
Labels: in progress

#2232 Fix type completion when type name conflicts
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/AbstractCompilationUnitBasedTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: bug

#2238 Update Maven plugin versions
  org.eclipse.jdt.ls.product/pom.xml
  pom.xml
Labels: dependencies

#2239 make use of GitHub functions for library update and security analysis
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: build/infra

#2243 Improve lambda completions
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: enhancement, completion

#2245 Fix Gradle project synchorization error when init script path contains spaces
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Labels: bug

#2249 Keep the temp init scripts on disk
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Labels: bug
