Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2022-04, with the labels that each got.

#2045 Change os.system to subprocess.run
  org.eclipse.jdt.ls.product/scripts/jdtls.py
Labels: build/infra

#2020 Advertise "friendly" Python startup wrapper a bit more prominently
  README.md
Labels: documentation

#2046 Fix the inlay hint for varargs methods
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
Labels: bug

#2028 Provide Java 18 support
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocSnippetStringEvaluator.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaElementLinks.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/fakejdk/18/rtstubs.jar
  org.eclipse.jdt.ls.tests/projects/eclipse/java18/.classpath
  org.eclipse.jdt.ls.tests/projects/eclipse/java18/.project
  org.eclipse.jdt.ls.tests/projects/eclipse/java18/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/java18/src/main/java/foo/bar/Foo.java
  org.eclipse.jdt.ls.tests/projects/eclipse/java18/src/main/java/org/sample/Test.java
  org.eclipse.jdt.ls.tests/projects/eclipse/wtpproject/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.tests/projects/gradle/invalid/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/.classpath
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/.project
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/.settings/org.eclipse.m2e.core.prefs
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/pom.xml
  org.eclipse.jdt.ls.tests/projects/maven/salut-java18/src/main/java/org/sample/Bar.java
  org.eclipse.jdt.ls.tests/projects/singlefile/java18a/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/singlefile/java18a/foo/bar/Foo.java
  org.eclipse.jdt.ls.tests/projects/singlefile/java18b/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/singlefile/java18b/foo/bar/Foo.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/ProjectUtilsTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LocalCorrectionQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ModifierCorrectionsQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/filesystem/InvisibleProjectMetadataFileTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporterTest.java
Labels: upstream, Java 18

#2047 Provide file & type comments for newly created compilation units
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeGenerationTemplate.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/UnresolvedTypesQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Labels: bug

#2042 Support insert replace completion capability
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionInsertReplaceCapabilityTest.java
Labels: completion

#2070 Fix NPE in isCompletionInsertReplaceSupport check
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
Labels: bug

#2077 Fix issue where JDT-LS's logback configuration was being ignored
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaLanguageServerPlugin.java
Labels: bug
