Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-03, with the labels that each got.

#2516 Reduce the target platform size by eliminating unnecessary bundles.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra

#2517 Update to m2e 2.2.1.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra

#2502 Implement method hierarchy through existing type hierarchy logic.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/pom.xml
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Five.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Four.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/One.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Six.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Three.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Two.java
  org.eclipse.jdt.ls.tests/projects/maven/type-hierarchy/src/main/java/org/example/Zero.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
Labels: enhancement

#2515 Add command to support decompiling class files
  org.eclipse.jdt.ls.core/plugin.xml
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DisassemblerContentProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
Labels: enhancement

#2547 fix duplicate results when search for *
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandlerTest.java
Labels: bug

#2551 Increase relevance of "create enum"
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/UnresolvedElementsSubProcessor.java
Labels: code-actions
