Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-07, with the labels that each got.

#2733 Check completion proposal is compatible or not.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: performance, content-assist

#2754 Fix param and exception addition/deletion in method signature refactoring
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/ChangeSignatureHandlerTest.java
Labels: bug

#2709 Fix wrong semantic highlighting due to out-of-date AST being used.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandler.java
Labels: bug, semantic highlighting

#2710 Smart semicolon autocorrect
  org.eclipse.jdt.ls.core/plugin.xml
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/BufferedDocumentScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitionScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitioner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastPartitioner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ICharacterScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IJavaPartitions.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IPartitionTokenScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IToken.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ITokenScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/Token.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionHandlerTest.java
Labels: enhancement

#2772 Fix call hierarchy position resolution #2771
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java
  org.eclipse.jdt.ls.tests/projects/eclipse/hello/src/org/sample/CallHierarchyGH2771.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandlerTest.java
Labels: bug

#2782 Fix the compiler arguments parsing failure
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupport.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
  org.eclipse.jdt.ls.tests/projects/gradle/apt/build.gradle
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Labels: bug, gradle

#2785 Filter out excessive logging of classfile parsing from m2e in "debug mode"
  org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
Labels: build/infra
