Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-12, with the labels that each got.

#2994 Update target platform to latest 4.31-I-builds.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: enhancement

#2995 Fix multiline semantic highlighting for 'implements', 'extends', and 'permits' keywords
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/semantictokens/SemanticTokensVisitor.java
  org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/src/main/java/foo/Constructors.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
Labels: bug, semantic highlighting

#2996 Add support for new headless quick fixes from upstream
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertMethodReferenceToLambdaTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/LambdaQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/VariableQuickFixTest.java
Labels: enhancement, code-actions

#2981 Introduce delegate command for java file paste
  org.eclipse.jdt.ls.core/plugin.xml
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
Labels: enhancement, client/communication

#2986 Consume javadoc pushdown from jdt.ui to jdt.core.manipulations
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SignatureHelpRequestor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/rename/RippleMethodFinder.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/AbstractJavaDocConverter.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2HTMLTextReader.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocCommentReader.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocHTMLPathHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocLocations.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDocSnippetStringEvaluator.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaElementLinks.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess2.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/html/SingleCharReader.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/html/SubstitutionTextReader.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/HoverHandlerTest.java
Labels: debt

#3000 Consume pushdown of partition logic to jdt.core.manipulations
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SmartDetectionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/BufferedDocumentScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitionScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastJavaPartitioner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/FastPartitioner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ICharacterScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IJavaPartitions.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IPartitionTokenScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/IToken.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/ITokenScanner.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/partition/Token.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: debt

#3002 The assignment to variable workingCopy has no effect
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
Labels: debt
