Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-10, with the labels that each got.

#2895 Update to latest Xtext and LSP4J
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies

#2906 Ensure line delimiter exists after the file header template.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/SnippetCompletionProposal.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/NewCUProposal.java
Labels: regression

#2886 Publish diagnostic for external files
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDocumentLifeCycleHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentLifeCycleHandlerTest.java
Labels: client/integration

#2727 "Surround with try/catch" Code Action
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractMethodTest.java
Labels: code-actions

#2922 Support named pipes for client/server communication.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ConnectionStreamFactory.java
Labels: client/communication
