Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-11, with the labels that each got.

#2951 Avoid refreshing bundles whose dependency closure includes JDT-LS.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BundleUtils.java
Labels: bug

#2943 Add Language Server Client - multilspy - to README.md
  README.md
Labels: documentation

#2956 Update maven-build-plugins
  org.eclipse.jdt.ls.product/pom.xml
  pom.xml
Labels: dependencies

#2965 Stop using Gson internal LinkedTreeMap in tests
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferencesTest.java
Labels: debt

#2964 Stop including o.e.core.net.win32.x86_64 fragments in products
  org.eclipse.jdt.ls.product/languageServer.product
  org.eclipse.jdt.ls.product/syntaxServer.product
Labels: debt

#2966 Enable licensecheck
  .github/workflows/licensecheck.yml
Labels: build/infra

#2970 Update commons-codec to 1.16.0
  org.eclipse.jdt.ls.product/languageServer.product
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra

#2973 Fix licensecheck running
  .github/workflows/licensecheck.yml
Labels: build/infra

#2974 Update buildship to 3.1.8
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra

#2976 Add maven.multiModuleProjectDirectory property
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Labels: maven

#2972 Support add/remove imported projects
  org.eclipse.jdt.ls.core/plugin.xml
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/EventType.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommand.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManager.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/ProjectsManagerTest.java
Labels: enhancement
