Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-01, with the labels that each got.

#2341 Share indexes among workspaces
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/IndexUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SharedIndexTest.java
Labels: enhancement, performance

#2404 vscode does not show type hierarchy on maven multi module
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.classpath
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.project
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project1/src/org/sample/First.java
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.classpath
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.project
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.jdt.ls.tests/projects/eclipse/gh2871/project2/src/org/sample/Second.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
Labels: bug

#2408 Use the Linux config on FreeBSD systems
  org.eclipse.jdt.ls.product/scripts/jdtls.py
Labels: build/infra

#2412 Reduce target platform size by making Xtext/Xtend requirements explicit.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: build/infra

#2420 Reduce the amount of logging from org.apache.http bundles.
  org.eclipse.jdt.ls.logback.appender/src/org/eclipse/jdt/ls/logback/appender/JavaLsConfigurator.java
Labels: bug, performance
