Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2023-02, with the labels that each got.

#2416 Do not require o.e.xtend.lib
  launch/jdt.ls.remote.server.launch
  launch/jdt.ls.socket-stream.launch
  launch/jdt.ls.socket-stream.syntaxserver.launch
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
Labels: build/infra

#2432 Update .project files from attempting project import with JDT-LS.
  .project
  .vscode/launch.json
  org.eclipse.jdt.ls.core/.project
  org.eclipse.jdt.ls.filesystem/.project
  org.eclipse.jdt.ls.filesystem/.settings/org.eclipse.core.resources.prefs
  org.eclipse.jdt.ls.filesystem/.settings/org.eclipse.m2e.core.prefs
  org.eclipse.jdt.ls.logback.appender/.project
  org.eclipse.jdt.ls.product/.project
  org.eclipse.jdt.ls.repository/.project
  org.eclipse.jdt.ls.tests.syntaxserver/.project
  org.eclipse.jdt.ls.tests/.project
Labels: build/infra

#2426 Add java.configuration.maven.defaultMojoExecutionAction
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenProjectImporter.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/StandardPreferenceManager.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/RenameHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SignatureHelpHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManagerTest.java
Labels: enhancement, maven

#2450 Enable formatting support in syntax server
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/BaseJDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxLanguageServer.java
  org.eclipse.jdt.ls.filesystem/.classpath
  org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests.syntaxserver/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxServerTest.java
  org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
Labels: enhancement, formatter

#2456 Add 'Convert String concatenation to Text Block' quick fix
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/IProposalRelevance.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/ConvertToTextBlockQuickFixTest.java
Labels: enhancement, code-actions

#2453 Only do context sensitive import rewrite when resolving completion items
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: performance

#2467 Accept types if they are imported when completion
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalRequestor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
Labels: content-assist

#2469 Update target platform to latest 4.27-I-builds.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies

#2472 Enable upgrading the Gradle version in projects without GradleBuild
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java
Labels: bug, regression

#2417 Use LSP4J 0.20.0
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTDelegateCommandHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintVisitor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/StandardProjectsManager.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver/SyntaxProjectsManager.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/ABOUT
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/ResolveTypeHierarchyItemParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/TypeHierarchyCapabilities.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/TypeHierarchyDirection.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/TypeHierarchyItem.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/TypeHierarchyParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHint.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintKind.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintLabelPart.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/proposed/InlayHintProvider.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommandTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/PrepareRenameHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporterTest.java
Labels: enhancement, dependencies

#2496 Check the client capability for inlay hints
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InlayHintsPreferenceChangeListener.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferencesTest.java
Labels: protocol
