Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2024-08, with the labels that each got.

#3212 Add Gradle 8.8 to compatibility check
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
Labels: gradle

#3238 Fix Gradle tests started with Java 23
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtils.java
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/build.gradle.kts
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleUtilsTest.java
Labels: build/infra

#3239 Fix failed cast to TypeDeclaration in file paste event
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java
Labels: bug

#3242 Fix AbstractQuickFixTest's evaluateCodeActions(..) logic.
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AbstractSelectionTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/ExtractFieldTest.java
Labels: build/infra

#3246 Update target platform to newer 4.33-I-builds (I20240820-1800).
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/TypeMismatchQuickFixTest.java
Labels: dependencies
