Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2024-03, with the labels that each got.

#3097 Update target platform to 4.31 release.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies

#3099 Update to LSP4J 0.22.0
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/extended/ProjectBuildParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/extended/ProjectConfigurationsUpdateParam.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/ResolveTypeHierarchyItemParams.java
  org.eclipse.jdt.ls.core/src/org/eclipse/lsp4j/legacy/typeHierarchy/TypeHierarchyItem.java
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceFolderChangeHandlerTest.java
Labels: dependencies

#3101 Use proper Unnamed Class API.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JDTUtils.java
Labels: upstream, dependencies

#3105 Update target platform to 2024-03 content
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies

#3110 Add missing files to the root of the project.
  CODE_OF_CONDUCT.md
  SECURITY.md
Labels: documentation

#3113 Fix tests failing to run on Mac
  org.eclipse.jdt.ls.tests/pom.xml
Labels: build/infra
