Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2024-06, with the labels that each got.

#3179 fix(scripts): add windows checks for jdtls.py
  org.eclipse.jdt.ls.product/scripts/jdtls.py
Labels: bug

#3188 Update target platform to 4.32 release.
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies

#3190 Report only one instance of a logged error through telemetry.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/LogHandler.java
Labels: telemetry

#3196 High CPU usage and memory consumption even if doing nothing
  .gitignore
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.tests/projects/eclipse/testnullable3/.classpath
  org.eclipse.jdt.ls.tests/projects/eclipse/testnullable3/.project
  org.eclipse.jdt.ls.tests/projects/eclipse/testnullable3/lib/org-netbeans-api-annotations-common-RELEASE200.jar
  org.eclipse.jdt.ls.tests/projects/eclipse/testnullable3/src/org/sample/Main.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/preferences/NullAnalysisTest.java
Labels: bug, performance

#3198 Add 'final' to 'Extract to local variable' result if requested
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/RefactorProposalUtility.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/GetRefactorEditHandlerTest.java
Labels: enhancement, code-actions

#3200 Update target platform to newer 4.33-I-builds (I20240621-0030).
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies
