Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2024-07, with the labels that each got.

#2792 Enable call hierarchy implementors
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
Labels: enhancement

#3215 Update target platform to newer 4.33-I-builds (I20240716-1800).
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/proposals/TypeMismatchSubProcessor.java
  org.eclipse.jdt.ls.product/languageServer.product
  org.eclipse.jdt.ls.product/syntaxServer.product
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/projects/maven/semantic-tokens/pom.xml
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/DiagnosticHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/SemanticTokensHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/EclipseProjectImporterTest.java
Labels: dependencies

#3218 Add java.diagnostic.filter to exclude files from diagnostic publishing.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/BaseDiagnosticsHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
Labels: enhancement, diagnostics

#3227 Update target platform to newer 4.33-I-builds (I20240728-1800).
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests/projects/eclipse/eclipsemaven/pom.xml
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/simple-gradle/build.gradle
  org.eclipse.jdt.ls.tests/projects/maven/buildhelped/pom.xml
  org.eclipse.jdt.ls.tests/projects/maven/salut/pom.xml
  org.eclipse.jdt.ls.tests/projects/maven/salut2/pom.xml
  org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/build.gradle
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/commands/ProjectCommandTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/JavadocQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/StringConcatenationQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/TypeMismatchQuickFixTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceDiagnosticsHandlerTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractGradleBasedTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/AbstractMavenBasedTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleBuildSupportTest.java
Labels: dependencies
