Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2024-05, with the labels that each got.

#3148 codeActionKinds not sent when CodeActionClientCapabilities is not dynamic.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CodeActionHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
Labels: protocol

#3142 Fix indentation for newline preceded by comma
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandler.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/handlers/FormatterHandlerTest.java
Labels: bug

#3169 Update to commons-codec:commons-codec:1.17.0
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
Labels: dependencies
