Repository eclipse-jdtls/eclipse.jdt.ls, pull requests merged in 2025-02, with the labels that each got.

#3373 Standardize on Gradle 8.5 to avoid multiple daemons at test runtime.
  org.eclipse.jdt.ls.tests/pom.xml
  org.eclipse.jdt.ls.tests/projects/gradle/android/build.gradle
  org.eclipse.jdt.ls.tests/projects/gradle/android/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/android/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/apt/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/apt/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-11/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-12/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-12/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-13/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-13/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-14/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-14/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-build-server/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-withoutjava/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/gradle-withoutjava/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/build.gradle.kts
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/kradle/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/metadata/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/metadata/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle1/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle2/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/nested/gradle3/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/no-gradlew/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/null-analysis/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/gradle/sample/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/gradle/sample/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/mixed/simple-gradle/gradle/wrapper/gradle-wrapper.properties
  org.eclipse.jdt.ls.tests/projects/multi-buildtools/gradle/wrapper/gradle-wrapper.jar
  org.eclipse.jdt.ls.tests/projects/multi-buildtools/gradle/wrapper/gradle-wrapper.properties
Labels: build/infra

#3375 Update gradle version to 8.5 in GradleProjectImporterTest
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporterTest.java
Labels: build/infra

#3374 Update some target platform dependencies to newer releases.
  org.eclipse.jdt.ls.core/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target
  org.eclipse.jdt.ls.tests.syntaxserver/META-INF/MANIFEST.MF
  org.eclipse.jdt.ls.tests/META-INF/MANIFEST.MF
Labels: dependencies

#3380 React to upstream changes preserving comments in lambda conversions.
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/AnonymousClassCreationToLambdaTest.java
Labels: upstream, code-actions

#3378 Support for inherited document symbols.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/commands/TypeHierarchyCommand.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CallHierarchyHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/SymbolUtils.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/TypeHierarchyHandler.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/lsp/JavaProtocolExtensions.java
Labels: enhancement, documentSymbols

#3383 New quick assist & cleanup for pattern instanceof if chain to switch.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpRegistry.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/cleanup/PatternInstanceofToSwitchCleanup.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/text/correction/QuickAssistProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/cleanup/CleanUpsTest.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/correction/AssistQuickFixTest21.java
Labels: enhancement, code-actions

#3385 Add GitHub workflow to automatically update target platform.
  .github/workflows/updateTarget.yml
  pom.xml
Labels: build/infra

#3379 Adjust Equinox launcher detection for mason-registry packaging.
  org.eclipse.jdt.ls.product/scripts/jdtls.py
Labels: client/integration

#3389 Attempt to use appropriate bot to automate pull request creation.
  .github/workflows/updateTarget.yml
Labels: build/infra

#3390 Set permissions for GITHUB_TOKEN in updateTarget workflow.
  .github/workflows/updateTarget.yml
Labels: build/infra

#3398 Detect more problems and support their quick fixes.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/QuickFixProcessor.java
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/ReturnTypeSubProcessor.java
Labels: enhancement, code-actions

#3400 Add 'Make static' refactoring.
  org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corrections/RefactorProcessor.java
  org.eclipse.jdt.ls.tests/src/org/eclipse/jdt/ls/core/internal/refactoring/MakeStaticTest.java
Labels: enhancement, code-actions
